### ISSUE TITLE
Model testing with object mocking : Call to undefined method Mock_Temperature_converter_88721996::method()

### ISSUE THREAD

**Issue by vikasgupta0159** [kenjis/ci-phpunit-test#186]
### While testing models with object mocks it doesn't works as expected:
this is my code:
```php
<?php
class Play_with_mocks_test extends TestCase{
	public function test_mocking_temperature_converter(){
		$mock = $this->getMockBuilder('Temperature_converter')->getMock();
		$mock->method('FtoC')->willReturn(99.9);
		// var_dump($mock);
		var_dump($mock, $mock->FtoC(100), $mock->CtoF(0));
		exit;
	}
}
```

and this is response:
```
PHP Fatal error:  Call to undefined method Mock_Temperature_converter_88721996::method() in D:\xampp\htdocs\unittesting\application\tests\models\Play_
with_mocks_test.php on line 5
PHP Stack trace:
PHP   1. {main}() D:\xampp\php\phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() D:\xampp\php\phpunit:46
PHP   3. PHPUnit_TextUI_Command->run() D:\xampp\php\pear\PHPUnit\TextUI\Command.php:129
PHP   4. PHPUnit_TextUI_TestRunner->doRun() D:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
PHP   5. PHPUnit_Framework_TestSuite->run() D:\xampp\php\pear\PHPUnit\TextUI\TestRunner.php:349
PHP   6. PHPUnit_Framework_TestSuite->runTest() D:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:745
PHP   7. PHPUnit_Framework_TestCase->run() D:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:775
PHP   8. PHPUnit_Framework_TestResult->run() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:776
PHP   9. PHPUnit_Framework_TestCase->runBare() D:\xampp\php\pear\PHPUnit\Framework\TestResult.php:648
PHP  10. PHPUnit_Framework_TestCase->runTest() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:831
PHP  11. ReflectionMethod->invokeArgs() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:976
PHP  12. Play_with_mocks_test->test_mocking_temperature_converter() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:976
PHP Fatal error:  Uncaught exception 'CIPHPUnitTestExitException' with message 'exit() called in _error_handler() function' in D:\xampp\htdocs\unittes
ting\system\core\Common.php:640
Stack trace:
#0 D:\xampp\htdocs\unittesting\system\core\Common.php(640): exit__(1)
#1 D:\xampp\htdocs\unittesting\system\core\Common.php(698): _error_handler(1, 'Call to undefin...', 'D:\\xampp\\htdocs...', 5)
#2 [internal function]: _shutdown_handler()
#3 {main}
  thrown in D:\xampp\htdocs\unittesting\system\core\Common.php on line 640
PHP Stack trace:
PHP   1. {main}() D:\xampp\php\phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() D:\xampp\php\phpunit:46
PHP   3. PHPUnit_TextUI_Command->run() D:\xampp\php\pear\PHPUnit\TextUI\Command.php:129
PHP   4. PHPUnit_TextUI_TestRunner->doRun() D:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
PHP   5. PHPUnit_Framework_TestSuite->run() D:\xampp\php\pear\PHPUnit\TextUI\TestRunner.php:349
PHP   6. PHPUnit_Framework_TestSuite->runTest() D:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:745
PHP   7. PHPUnit_Framework_TestCase->run() D:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:775
PHP   8. PHPUnit_Framework_TestResult->run() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:776
PHP   9. PHPUnit_Framework_TestCase->runBare() D:\xampp\php\pear\PHPUnit\Framework\TestResult.php:648
PHP  10. PHPUnit_Framework_TestCase->runTest() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:831
PHP  11. ReflectionMethod->invokeArgs() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:976
PHP  12. Play_with_mocks_test->test_mocking_temperature_converter() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:976

Fatal error: Call to undefined method Mock_Temperature_converter_88721996::method() in D:\xampp\htdocs\unittesting\application\tests\models\Play_with_
mocks_test.php on line 5

Call Stack:
    0.0002     122296   1. {main}() D:\xampp\php\phpunit:0
    0.0035     357832   2. PHPUnit_TextUI_Command::main() D:\xampp\php\phpunit:46
    0.0036     361232   3. PHPUnit_TextUI_Command->run() D:\xampp\php\pear\PHPUnit\TextUI\Command.php:129
    0.0798    3593768   4. PHPUnit_TextUI_TestRunner->doRun() D:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
    0.1350    4034016   5. PHPUnit_Framework_TestSuite->run() D:\xampp\php\pear\PHPUnit\TextUI\TestRunner.php:349
    0.1643    5243816   6. PHPUnit_Framework_TestSuite->runTest() D:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:745
    0.1643    5244144   7. PHPUnit_Framework_TestCase->run() D:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:775
    0.1644    5244856   8. PHPUnit_Framework_TestResult->run() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:776
    0.1866    5286376   9. PHPUnit_Framework_TestCase->runBare() D:\xampp\php\pear\PHPUnit\Framework\TestResult.php:648
    0.1911    5400736  10. PHPUnit_Framework_TestCase->runTest() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:831
    0.1912    5401248  11. ReflectionMethod->invokeArgs() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:976
    0.1912    5401312  12. Play_with_mocks_test->test_mocking_temperature_converter() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:976


A PHP Error was encountered

Severity:    Error
Message:     Call to undefined method Mock_Temperature_converter_88721996::method()
Filename:    D:\xampp\htdocs\unittesting\application\tests\models\Play_with_mocks_test.php
Line Number: 5

Backtrace:


Fatal error: Uncaught exception 'CIPHPUnitTestExitException' with message 'exit() called in _error_handler() function' in D:\xampp\htdocs\unittesting\
system\core\Common.php on line 640

Call Stack:
    0.0002     122296   1. {main}() D:\xampp\php\phpunit:0
    0.0035     357832   2. PHPUnit_TextUI_Command::main() D:\xampp\php\phpunit:46
    0.0036     361232   3. PHPUnit_TextUI_Command->run() D:\xampp\php\pear\PHPUnit\TextUI\Command.php:129
    0.0798    3593768   4. PHPUnit_TextUI_TestRunner->doRun() D:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
    0.1350    4034016   5. PHPUnit_Framework_TestSuite->run() D:\xampp\php\pear\PHPUnit\TextUI\TestRunner.php:349
    0.1643    5243816   6. PHPUnit_Framework_TestSuite->runTest() D:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:745
    0.1643    5244144   7. PHPUnit_Framework_TestCase->run() D:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:775
    0.1644    5244856   8. PHPUnit_Framework_TestResult->run() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:776
    0.1866    5286376   9. PHPUnit_Framework_TestCase->runBare() D:\xampp\php\pear\PHPUnit\Framework\TestResult.php:648
    0.1911    5400736  10. PHPUnit_Framework_TestCase->runTest() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:831
    0.1912    5401248  11. ReflectionMethod->invokeArgs() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:976
    0.1912    5401312  12. Play_with_mocks_test->test_mocking_temperature_converter() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:976

CIPHPUnitTestExitException: exit() called in _error_handler() function in D:\xampp\htdocs\unittesting\system\core\Common.php on line 640

Call Stack:
    0.0002     122296   1. {main}() D:\xampp\php\phpunit:0
    0.0035     357832   2. PHPUnit_TextUI_Command::main() D:\xampp\php\phpunit:46
    0.0036     361232   3. PHPUnit_TextUI_Command->run() D:\xampp\php\pear\PHPUnit\TextUI\Command.php:129
    0.0798    3593768   4. PHPUnit_TextUI_TestRunner->doRun() D:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
    0.1350    4034016   5. PHPUnit_Framework_TestSuite->run() D:\xampp\php\pear\PHPUnit\TextUI\TestRunner.php:349
    0.1643    5243816   6. PHPUnit_Framework_TestSuite->runTest() D:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:745
    0.1643    5244144   7. PHPUnit_Framework_TestCase->run() D:\xampp\php\pear\PHPUnit\Framework\TestSuite.php:775
    0.1644    5244856   8. PHPUnit_Framework_TestResult->run() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:776
    0.1866    5286376   9. PHPUnit_Framework_TestCase->runBare() D:\xampp\php\pear\PHPUnit\Framework\TestResult.php:648
    0.1911    5400736  10. PHPUnit_Framework_TestCase->runTest() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:831
    0.1912    5401248  11. ReflectionMethod->invokeArgs() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:976
    0.1912    5401312  12. Play_with_mocks_test->test_mocking_temperature_converter() D:\xampp\php\pear\PHPUnit\Framework\TestCase.php:976
    0.2089    5559896  13. _shutdown_handler() D:\xampp\htdocs\unittesting\system\core\Common.php:0
    0.2095    5560536  14. _error_handler() D:\xampp\htdocs\unittesting\system\core\Common.php:698
    0.2175    5601656  15. exit__() D:\xampp\htdocs\unittesting\system\core\Common.php:640
```

and var_dump of $mock shows something like this:
```
class Mock_Temperature_converter_50ddf70c#241 (1) {
  private $__phpunit_invocationMocker =>
  NULL
}
```

I am using PHPUnit 3.7.21
and Codeigniter 3.1.4

**Comment by vikasgupta0159** [comment]
Solved : I was using an older version of phpunit
switched to version 5.7 and everything started working.
