### ISSUE TITLE
PHP Fatal error: Class 'TestCase' not found 

### ISSUE THREAD

**Issue by JonaMX** [kenjis/ci-phpunit-test#229]
Here's the error output that I'm getting:
```
~/D/T/p/c/a/tests ❯❯❯ ../../vendor/bin/phpunit controllers/Welcome_test.php

PHP Fatal error:  Class 'TestCase' not found in /Users/Jonatan/Documents/TS/projects/carrier-suite/application/tests/controllers/Welcome_test.php on line 12

Fatal error: Class 'TestCase' not found in /Users/Jonatan/Documents/TS/projects/carrier-suite/application/tests/controllers/Welcome_test.php on line 12

A PHP Error was encountered

Severity:    Error
Message:     Class 'TestCase' not found
Filename:    /Users/Jonatan/Documents/TS/projects/carrier-suite/application/tests/controllers/Welcome_test.php
Line Number: 12

Backtrace:

PHP Fatal error:  Uncaught exception 'CIPHPUnitTestExitException' with message 'exit() called in _error_handler() function' in /Users/Jonatan/Documents/TS/projects/carrier-suite/system/core/Common.php:635
Stack trace:
#0 /Users/Jonatan/Documents/TS/projects/carrier-suite/system/core/Common.php(635): exit__(1)
#1 /Users/Jonatan/Documents/TS/projects/carrier-suite/system/core/Common.php(692): _error_handler(1, 'Class 'TestCase...', '/Users/Jonatan/...', 12)
#2 [internal function]: _shutdown_handler()
#3 {main}
  thrown in /Users/Jonatan/Documents/TS/projects/carrier-suite/system/core/Common.php on line 635

Fatal error: Uncaught exception 'CIPHPUnitTestExitException' with message 'exit() called in _error_handler() function' in /Users/Jonatan/Documents/TS/projects/carrier-suite/system/core/Common.php:635
Stack trace:
#0 /Users/Jonatan/Documents/TS/projects/carrier-suite/system/core/Common.php(635): exit__(1)
#1 /Users/Jonatan/Documents/TS/projects/carrier-suite/system/core/Common.php(692): _error_handler(1, 'Class 'TestCase...', '/Users/Jonatan/...', 12)
#2 [internal function]: _shutdown_handler()
#3 {main}
  thrown in /Users/Jonatan/Documents/TS/projects/carrier-suite/system/core/Common.php on line 635

```

this is how my `Welcome_Test.php` file looks like:
```php
<?php

class Welcome_test extends TestCase
{
	public function test_index()
	{
		$output = $this->request('GET', ['Welcome', 'index']);
		$this->assertContains('<title>Welcome to CodeIgniter</title>', $output);
	}

	public function test_method_404()
	{
		$this->request('GET', ['Welcome', 'method_not_exist']);
		$this->assertResponseCode(404);
	}

	public function test_APPPATH()
	{
		$actual = realpath(APPPATH);
		$expected = realpath(__DIR__ . '/../..');
		$this->assertEquals(
			$expected,
			$actual,
			'Your APPPATH seems to be wrong. Check your $application_folder in tests/Bootstrap.php'
		);
	}
}

```

These are the versions of my packages:
```
~/D/T/p/c/a/tests ❯❯❯ ../../vendor/bin/phpunit --version
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

~/D/T/p/c/a/tests ❯❯❯ php --version
PHP 5.6.33 (cli) (built: Jan 17 2018 13:29:46)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

I already configured the `config.php` to use `$config['composer_autoload'] = "./vendor/autoload.php";` but I just can't make it work, am I missing something?

**Comment by JonaMX** [comment]
Never mind, I figured this out, turns out that it was a corrupted installation, had to reinstall and it worked. Thanks anyway
