### ISSUE TITLE
Test break when testing a function

### ISSUE THREAD

**Issue by ayokay123** [kenjis/ci-phpunit-test#359]
my test used to work normally without any problems when I tried to test this function the test breaks
I got this error
```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

.
.{"success":false,"message":"<p>The percentage field must contain only numbers.<\/p>\n"}
```
this is the test
```php
public function test_save()
    {
        $output = $this->request(
            'POST',
            ['Foo', 'save'],
            [
                'title'=> 'fsfdsfs',
                'percentage'=> 'aaaaaa'
            ]
        );
        $this->assertContains('The percentage field must', $output);
    }
```
and this the function that I'm testing 
```php
function save() {

        validate_submitted_data(array(
            "id" => "numeric",
            "title" => "required",
            "percentage" => "required|numeric|greater_than[0]|less_than[100]"
        ));
        $id = $this->input->post('id');
        $data = array(
            "title" => $this->input->post('title'),
            "percentage" => $this->input->post('percentage')
        );
        $save_id = $this->Foo_model->save($data, $id);
        if ($save_id) {
            echo json_encode(array("success" => true, 'message' => lang('record_saved')));
        } else {
            echo json_encode(array("success" => false, 'message' => lang('error_occurred')));
        }
    }
```

**Comment by kenjis** [comment]
It seems `{"success":false,"message":"<p>The percentage field must contain only numbers.<\/p>\n"}` is the controller's output. And you see it,  because phpunit died after the controller execution.

Probably RestServer calls `die()`?

You have no errors on test execution.

> Error:         No code coverage driver is available

This error means just you can't get code coverage reporting.

**Comment by ayokay123** [comment]
it's a weird behavior it only happens when there's an error in the input

**Comment by kenjis** [comment]
What is the input?
What is the error?

**Comment by ayokay123** [comment]
i'm testing a function in my controller that returns this 
        ```
if ($save_id) {
            echo json_encode(array("success" => true, 'message' => lang('record_saved')));
        } else {
            echo json_encode(array("success" => false, 'message' => lang('error_occurred')));
        }
```
I made a test for it when i put valid input the assertion works perfectly but when i put invalid input(i have some conditions in the controller) the test breaks immediately after returning `echo json_encode(array("success" => false, 'message' => lang('error_occurred')));`

**Comment by kenjis** [comment]
Do you mean when `$save_id` is false, the test fails, phpunit dies?

**Comment by ayokay123** [comment]
exactly

**Comment by kenjis** [comment]
It is very weird. It seems there is no difference between true case and false case.
Both just echoes json string.

**Comment by ayokay123** [comment]
I tried to run PHPUnit with the flag `--process-isolation`
I got more info but I'm not sure if it's useful 
```
There was 1 error:

1) Taxes_test::test_taxe_save_wrong_percentage
PHPUnit\Framework\Exception: {"success":false,"message":"<p>The percentage field must contain a number less than or equal to 100.<\/p>\n"}

/var/www/html/vendor/phpunit/phpunit/phpunit:61

Caused by
ErrorException: unserialize(): Error at offset 0 of 110 bytes in /var/www/html/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php:250
Stack trace:
#0 [internal function]: PHPUnit\Util\PHP\AbstractPhpProcess->PHPUnit\Util\PHP\{closure}(8, 'unserialize(): ...', '/var/www/html/v...', 250, Array)
#1 /var/www/html/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php(250): unserialize('\n{"success":fal...')
#2 /var/www/html/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php(171): PHPUnit\Util\PHP\AbstractPhpProcess->processChildResult(Object(Taxes_test), Object(PHPUnit\Framework\TestResult), '\n{"success":fal...', '')
#3 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(794): PHPUnit\Util\PHP\AbstractPhpProcess->runTestJob('<?php\nuse PHPUn...', Object(Taxes_test), Object(PHPUnit\Framework\TestResult))
#4 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(746): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#5 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(652): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#6 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(206): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(162): PHPUnit\TextUI\Command->run(Array, true)
#8 /var/www/html/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#9 {main}
ERRORS!
```

**Comment by kenjis** [comment]
I'm also not sure if it's useful.

Step execution of PHPUnit testing with Xdebug may help you.

**Comment by ayokay123** [comment]
the problem is try-catch doesn't work on PHPUnit I think

**Comment by ayokay123** [comment]
I fixed it by enabling Monkey Patching

**Comment by ayokay123** [comment]
i got this error when i try to run all my tests
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 37748736 bytes) in /var/www/html/application/tests/_ci_phpunit_test/patcher/3.x/MonkeyPatchManager.php on line 54`

**Comment by ayokay123** [comment]
i got this error when i try to run all my tests
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 37748736 bytes) in /var/www/html/application/tests/_ci_phpunit_test/patcher/3.x/MonkeyPatchManager.php on line 54

**Comment by kenjis** [comment]
If you still have this problem, feel free to reopen.
